"""Tests for the Phase 6 closure record.

WHY THIS EXISTS
---------------
Phase 6 closes with a two-sided status: the Run 1 adapter is **usable/verified** but
**acceptance-rejected**. That pairing is easy to degrade later in two opposite ways:

  * someone "tidies" the record into a single `ACCEPTED` because the adapter works; or
  * someone "tidies" it into a plain `REJECTED` and the working adapter is discarded.

Both are failures. These tests re-derive the closure's claims from the evidence files
and fail if the record and the evidence disagree, and they assert that **both**
rejection records survive and that the val-split `ACCEPTED` is still marked as not
final.

The closure record is generated by `scripts/phase6_close.py`, which reads the evidence
rather than restating it. These tests are the independent second pass: they do not
import the record's numbers from the generator, they recompute them from
`test_adjudication.json` and compare.
"""

from __future__ import annotations

import importlib.util
import json
import math
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "phase6_close.py"
EVIDENCE_DIR = REPO_ROOT / "artifacts" / "vlm" / "run1_test_recovery"
CLOSURE_PATH = REPO_ROOT / "artifacts" / "vlm" / "phase6_closure.json"
ADJUDICATION_PATH = EVIDENCE_DIR / "test_adjudication.json"
RECOVERY_MANIFEST_PATH = EVIDENCE_DIR / "run_manifest.json"
RUN1_MANIFEST_PATH = Path(r"D:/New folder (2)/New folder (3)/_x/run_manifest.json")


def _load_module():
    spec = importlib.util.spec_from_file_location("phase6_close", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load(path: Path):
    if not path.is_file():
        pytest.skip(f"evidence not present: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def closure():
    return _load(CLOSURE_PATH)


@pytest.fixture(scope="module")
def adjudication():
    return _load(ADJUDICATION_PATH)


# ---------------------------------------------------------------------------
# 1. the record exists and carries the two-sided status
# ---------------------------------------------------------------------------
def test_closure_record_exists_and_is_generated(closure):
    assert closure["kind"] == "phase6_closure"
    assert closure["phase"] == 6
    assert closure["status"] == "CLOSED"
    assert closure["generated_at"]


def test_adapter_is_marked_usable_verified_but_acceptance_rejected(closure):
    adapter = closure["production_adapter"]
    assert adapter["use_status"] == "USABLE_VERIFIED"
    assert adapter["acceptance_status"] == "REJECTED"
    # The distinction must be explained, not just asserted.
    assert "Verified" in closure["verified_vs_accepted"]
    assert "Accepted" in closure["verified_vs_accepted"]


def test_closure_never_claims_the_run_was_accepted(closure):
    """The single most important guard: no ACCEPTED may be laundered into the status."""
    assert closure["production_adapter"]["acceptance_status"] != "ACCEPTED"
    assert closure["why_acceptance_rejected"]["status"] == "REJECTED"
    assert closure["why_acceptance_rejected"]["decision_split"] == "test"
    # The disclaimer list must actually disclaim the acceptance.
    assert any(
        "not claim run 1 was accepted" in phrase.lower().replace("**", "")
        for phrase in closure["what_closure_does_not_claim"]
    )


def test_adapter_was_not_retrained_or_modified(closure):
    adapter = closure["production_adapter"]
    assert adapter["retrained_for_closure"] is False
    assert adapter["modified_for_closure"] is False
    assert closure["rule_unchanged_by_closure"] is True
    assert closure["not_a_retrain"] is True


# ---------------------------------------------------------------------------
# 2. both rejection records are preserved
# ---------------------------------------------------------------------------
def test_v001_val_rejection_is_preserved(closure):
    record = closure["preserved_records"]["v001_val_rejected"]
    assert record["rule_version"] == "v001"
    assert record["split"] == "val"
    assert record["status"] == "REJECTED"
    assert record["immutable"] is True
    assert len(record["class_failures"]) == 3
    assert record["val_delta_pp"] == 42.0
    # Run 1's test metrics were never persisted — the V2 short-circuit returned first.
    assert record["test_delta_pp"] is None


def test_v002_independent_test_rejection_is_preserved(closure):
    record = closure["preserved_records"]["v002_independent_test_rejected"]
    assert record["rule_version"] == "v002"
    assert record["split"] == "test"
    assert record["status"] == "REJECTED"
    assert record["immutable"] is True
    assert len(record["class_failures"]) == 1
    assert record["test_delta_pp"] == 49.5


def test_val_split_accept_is_recorded_but_marked_not_final(closure):
    """It must stay visible AND be explicitly disqualified, not silently dropped."""
    record = closure["preserved_records"]["v002_val_accepted_NOT_final"]
    assert record["status"] == "ACCEPTED"
    assert record["superseded_by"] == "v002_independent_test_rejected"
    assert "NOT final acceptance" in record["role"]
    assert "§7.4" in record["role"] or "7.4" in record["role"]


def test_the_two_run1_digests_are_recorded_separately_with_a_warning(closure):
    """file sha256 and the manifest's internal hash are different values."""
    entry = closure["evidence_index"]["run1_manifest"]
    assert entry["file_sha256"] != entry["internal_manifest_hash"]
    assert "NOT the file digest" in entry["warning"]


# ---------------------------------------------------------------------------
# 3. the recorded regression is re-derived from the adjudication, not trusted
# ---------------------------------------------------------------------------
def test_failing_class_arithmetic_is_recomputed_from_the_adjudication(closure, adjudication):
    rows = {r["class"]: r for r in adjudication["per_class_test"]}
    counts = adjudication["baseline_test"]["per_class_counts"]
    base = adjudication["baseline_test"]["per_class_accuracy"]
    adap = adjudication["adapted_test"]["per_class_accuracy"]

    for failure in closure["why_acceptance_rejected"]["regression"]["failing_classes"]:
        name = failure["class"]
        n = counts[name]
        b, a = base[name], adap[name]
        drop = (b - a) * 100.0
        lost = round((b - a) * n)
        se = math.sqrt(max(b * (1 - b) + a * (1 - a), 1e-12) / n)
        z = (b - a) / se

        assert failure["n_questions"] == n
        assert failure["drop_pp"] == pytest.approx(drop, abs=1e-3)
        assert failure["lost_questions"] == lost
        assert failure["z"] == pytest.approx(z, abs=1e-3)
        # And it must genuinely fail BOTH halves of v002, not one.
        assert lost >= 4
        assert z >= 1.96
        # The per-class table stores adapted-baseline, so it is the NEGATIVE of the
        # drop. Comparing them without the sign flip is a silent way to pass a wrong
        # number, so assert the sign explicitly.
        assert rows[name]["delta_pp"] == pytest.approx(-drop, abs=1e-2)


def test_exactly_one_class_fails_and_the_counts_are_consistent(closure, adjudication):
    reg = closure["why_acceptance_rejected"]["regression"]
    rows = adjudication["per_class_test"]

    positive = sum(1 for r in rows if r["delta_pp"] > 0)
    zero = sum(1 for r in rows if r["delta_pp"] == 0)

    assert reg["n_classes_total"] == len(rows) == 19
    assert reg["n_classes_improved"] == positive
    assert reg["n_classes_held"] == zero
    assert reg["n_classes_failed"] == 1
    # Guard the claim I got wrong once by hand: it is 16 improved-or-held, not 18.
    assert positive + zero == 16


def test_the_regression_is_documented_as_not_a_split_artefact(closure):
    reg = closure["why_acceptance_rejected"]["regression"]
    assert "both" in reg["why_not_a_split_artefact"].lower() or "BOTH" in reg["why_not_a_split_artefact"]
    # It cites the val-split drop that motivated v001's flag.
    assert "6.4516" in reg["why_not_a_split_artefact"]
    # And the residual risk is recorded rather than hidden.
    assert "33" in reg["residual_risk"]
    assert "not resolved" in reg["residual_risk"]


# ---------------------------------------------------------------------------
# 4. the forward rule freezes Run 1
# ---------------------------------------------------------------------------
def test_forward_rule_freezes_run1_and_forbids_rewriting_it(closure):
    rule = closure["forward_rule"]
    assert rule["run1_is_frozen"] is True
    assert "new experiment/version" in rule["statement"]
    assert "MUST NOT" in rule["statement"]

    must_not = " ".join(rule["must_not"]).lower()
    assert "retrain or modify the run 1 adapter" in must_not
    assert "overwrite" in must_not

    requires = " ".join(rule["new_work_requires"]).lower()
    assert "independent test-split adjudication" in requires


# ---------------------------------------------------------------------------
# 5. the generator refuses to produce an optimistic record
# ---------------------------------------------------------------------------
def test_generator_refuses_when_the_adjudication_is_not_rejected(tmp_path, monkeypatch):
    if not RUN1_MANIFEST_PATH.is_file():
        pytest.skip("run 1 manifest not present")
    module = _load_module()
    tampered = json.loads(ADJUDICATION_PATH.read_text(encoding="utf-8"))
    tampered["decision"]["status"] = "ACCEPTED"
    path = tmp_path / "tampered_adjudication.json"
    path.write_text(json.dumps(tampered), encoding="utf-8")
    monkeypatch.setattr(module, "ADJUDICATION_PATH", path)

    with pytest.raises(SystemExit, match="not REJECTED"):
        module.main([])


def test_generator_refuses_when_the_decision_split_is_not_test(tmp_path, monkeypatch):
    if not RUN1_MANIFEST_PATH.is_file():
        pytest.skip("run 1 manifest not present")
    module = _load_module()
    tampered = json.loads(ADJUDICATION_PATH.read_text(encoding="utf-8"))
    tampered["decision_split"] = "val"
    path = tmp_path / "tampered_split.json"
    path.write_text(json.dumps(tampered), encoding="utf-8")
    monkeypatch.setattr(module, "ADJUDICATION_PATH", path)

    with pytest.raises(SystemExit, match="did not decide on the test split"):
        module.main([])


def test_regenerating_the_record_reproduces_it(closure):
    """The record must be a pure function of the evidence (modulo the timestamp)."""
    if not RUN1_MANIFEST_PATH.is_file():
        pytest.skip("run 1 manifest not present")
    module = _load_module()
    run1 = json.loads(RUN1_MANIFEST_PATH.read_text(encoding="utf-8"))
    recovery = json.loads(RECOVERY_MANIFEST_PATH.read_text(encoding="utf-8"))
    adjudication = json.loads(ADJUDICATION_PATH.read_text(encoding="utf-8"))

    rebuilt = module.build_closure(run1, recovery, adjudication)
    rebuilt.pop("generated_at")
    original = dict(closure)
    original.pop("generated_at")
    assert rebuilt == original


# ---------------------------------------------------------------------------
# 6. integration: how the production adapter is actually enabled
# ---------------------------------------------------------------------------
def test_integration_records_the_env_var_mechanism(closure):
    how = closure["production_adapter"]["how_enabled"]
    assert how["env_var"] == "SATQUERY_VLM_ADAPTER"
    assert "environment variable" in how["mechanism"]
    # It must name where the resolution happens, so the claim is checkable.
    assert "specialists/vqa/model.py" in how["resolved_in"]


def test_integration_names_the_files_needed_to_attach(closure):
    adapter = closure["production_adapter"]
    assert set(adapter["files_required_for_attachment"]) == {
        "adapter_model.safetensors",
        "adapter_config.json",
    }


def test_the_adapter_sha256_name_collision_is_recorded(closure):
    """Two different digests share one name; losing this note invites a false alarm."""
    traps = " ".join(closure["production_adapter"]["known_traps"])
    assert "training/vlm/artifact.py" in traps
    assert "specialists/vqa/model.py" in traps
    assert "5c6b8631" in traps and "07c76a75" in traps
    assert "TREE HASH" in traps and "FILE sha256" in traps


def test_the_not_checkpoint_2000_finding_is_recorded(closure):
    traps = " ".join(closure["production_adapter"]["known_traps"])
    assert "NOT checkpoint-2000" in traps
    assert "7273588e" in traps and "bf249943" in traps


def test_reconstruction_path_is_recorded(closure):
    rec = closure["production_adapter"]["reconstruction"]
    assert "phase6_realbundle.zip" in rec["source"]
    assert rec["entry_prefix"] == "phase6_adapter/"
    assert len(rec["verify_against"]) >= 2


def test_artifact_verification_is_folded_in_when_present(closure):
    """If the verifier's record exists it must be reflected, and never overstated."""
    av = closure["artifact_verification"]
    if not av["available"]:
        # Absence must be explicit, never a silent placeholder pass.
        assert "NOT performed" in av["note"]
        return
    assert av["verdict"] in {"verified", "discrepancy"}
    assert av["tree_hash_matches"] is True
    assert av["computed_tree_hash"] == closure["production_adapter"]["adapter_tree_sha256"]


def test_artifact_verification_manifest_check_is_recorded(closure):
    """The manifest check is what makes 'verified' mean 'these are our bytes'."""
    av = closure["artifact_verification"]
    if not av["available"]:
        pytest.skip("adapter_verification.json not present")
    mc = av["manifest_check"]
    assert mc["n_files_in_manifest"] == 14
    assert mc["n_files_on_disk"] == 14
    assert mc["missing_files"] == []
    assert mc["mismatched_files"] == []
    assert mc["extra_files"] == []
    assert mc["clean"] is True


def test_artifact_verification_records_promoted_adapter_is_not_a_checkpoint(closure):
    """The provenance trap: the promoted weights are neither intermediate checkpoint."""
    av = closure["artifact_verification"]
    if not av["available"]:
        pytest.skip("adapter_verification.json not present")
    promoted = av["promoted_adapter"]
    assert promoted["is_a_checkpoint"] is False
    assert promoted["all_three_digests_distinct"] is True
    assert promoted["sha256"] == av["weights_file_sha256"]
    # Re-derive the finding: the three weight digests must genuinely differ.
    digests = {promoted["sha256"], *promoted["checkpoint_weight_digests"].values()}
    assert len(digests) == 3
    # And the promoted digest is NOT the checkpoint-2000 digest.
    assert promoted["sha256"] != promoted["checkpoint_weight_digests"][
        "checkpoint-2000/adapter_model.safetensors"
    ]


def test_artifact_verification_findings_and_blockers_are_carried_through(closure):
    av = closure["artifact_verification"]
    if not av["available"]:
        pytest.skip("adapter_verification.json not present")
    ids = {f["id"] for f in av["findings"]}
    assert "F2_adapter_sha256_name_collision" in ids
    assert "F4_promoted_adapter_is_not_a_checkpoint" in ids
    # Every carried finding must keep a summary -- an id alone is not a finding.
    assert all(f["summary"] for f in av["findings"])
    # No blocking issue may be quietly dropped.
    assert av["blocking_issues"] == []


def test_artifact_verification_records_read_only_and_loadability(closure):
    av = closure["artifact_verification"]
    if not av["available"]:
        pytest.skip("adapter_verification.json not present")
    assert av["read_only"] is True
    assert av["loadability_detail"]["performed"] is True
    assert av["loadable_via_production_path"] is True
    assert av["directory_self_consistent_with_own_manifest"] is True
    # An amendment is a fact about the record and must be visible, not hidden.
    assert av["amended_at"]
